; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:panneau1]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = board1
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/panneau1/*.cpp>
monitor_port = /dev/ttyACM0 #replace by the correct port (COM are written as COM[0] directly)
build_flags =
    '-D BOARD_NUM = 1'

[env:panneau2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = board2
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/panneau2/*.cpp>
monitor_port = /dev/ttyACM1 #replace this port as well
build_flags =
    '-D BOARD_NUM = 2'
