; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:A_panneau_lateral_gauche]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = A_panneau_lateral_gauche
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/A_panneau_lateral_gauche/*.cpp>
lib_deps =
	fastled/FastLED@^3.9.16
	robtillaart/ADS1X15@^0.5.2
	gbr1/rp2040-encoder-library@^0.2.0

[env:A_panneau_bas_gauche]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = A_panneau_bas_gauche
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/A_panneau_bas_gauche/*.cpp>
lib_deps =
	fastled/FastLED@^3.9.16
	robtillaart/ADS1X15@^0.5.2
	gbr1/rp2040-encoder-library@^0.2.0

[env:B_panneau_central_haut]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = B_panneau_central_haut
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/B_panneau_central_haut/*.cpp>
lib_deps =
	fastled/FastLED@^3.9.16
	robtillaart/ADS1X15@^0.5.2
	gbr1/rp2040-encoder-library@^0.2.0

[env:B_panneau_central_bas]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = B_panneau_central_bas
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/B_panneau_central_bas/*.cpp>
lib_deps =
	fastled/FastLED@^3.9.16
	robtillaart/ADS1X15@^0.5.2
	gbr1/rp2040-encoder-library@^0.2.0

[env:Manette_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = Manette_test
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<**/Manette_test/*.cpp>
lib_deps =
	fastled/FastLED@^3.9.16
	robtillaart/ADS1X15@^0.5.2
	gbr1/rp2040-encoder-library@^0.2.0
